FROM alpine

RUN apk -U upgrade && \
apk add nodejs && \
apk add npm && \
apk add nano && \
mkdir /home/jwt /home/jwt/config /home/jwt/middleware /home/jwt/model && \
cd /home/jwt/

WORKDIR /home/jwt/

COPY app.js /home/jwt/
COPY index.js /home/jwt/
COPY user.js /home/jwt/model
COPY database.js /home/jwt/config/
COPY auth.js /home/jwt/middleware/
COPY .env /home/jwt/

RUN npm init -y
RUN npm install mongoose express jsonwebtoken dotenv bcryptjs nodemon
